@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods
left to right direction


'title Domain Model

'class Platform {
'  -description
'}

class RealEstate {
    name
    address
    descriptions
    website
    phoneNumber
    email
    vatNumber
    logo
}
class RealEstateAgent {

}
class Client {

}
class Owner {

}
abstract class User {
    name
    email
    password
    position
}
abstract class Proprietary {
    name
    Tipo
    address
    descriptions
    vender:boolean
    render:boolean
}
class Land{
}

class Apartment{
numberOfRooms
numberOfBathrooms
numberOfFloors
numberOfGarages
Equipaments

}
class House{
numberOfRooms
    numberOfBathrooms
    numberOfFloors
    numberOfGarages
    Equipaments
    Basement: boolean
    inhabited  loft: boolean
    Sun exposure: boolean

}
class Advertisement{
    owner
    descriptions
    RealEstateAgent
    cost
}
class Schedule{
    date
    time
    descriptions
}
class visit{
    Client
    date
    time
    descriptions
    RealEstateAgent
    ResultOfTheVisit : boolean
}
class Order{
    descriptions
    client
    owner
    Proprietary

}

enum TipoOrder{
tipo
}
class StoreNetWork{

}
class Store{
}
class StoreManager{
}
class NetWorkManager{
}
class Administrator{
}


RealEstate "1"--"1" StoreNetWork
StoreNetWork "1"--"*" Store
Store "1"--"1" StoreManager
StoreNetWork "1"--"1" NetWorkManager

Administrator "1"--"*" User : Create

Administrator --|> User
StoreManager --|> User
NetWorkManager --|> User
RealEstateAgent  --|>  User
Owner  --|>  User
Client  --|>  User
RealEstate "1"--" 0..*" User : has
House  --|>  Proprietary
Apartment  --|>  Proprietary
RealEstate "1"--"0..*" Proprietary : has
Land  --|>  Proprietary
Owner "1"--"0..*"Advertisement : has or Request
RealEstateAgent "1"--"0..*"Advertisement : Publishes
Client "1"--"1"visit : request
RealEstateAgent "1"--"1"visit : attends
RealEstateAgent "1"--"0..*"Schedule : has
Order "0..*"--"1" TipoOrder : has


@enduml