@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber
actor "Agent" as Agent
participant ":System" as System

activate Agent

    Agent -> System : Requests to see the list of visit requests
    activate System

    System --> Agent : Requests begin data and end data of the visit requests
    deactivate System
    "Agent" -> System : fill the requested data

    activate System

    System --> Agent : Shows list of visit requests of the agent
    deactivate System


deactivate Agent

@enduml