@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Owner" as Owner
participant ":System" as System

activate "Owner"

Owner -> System : "Asks to submite a new request"
activate System

System --> Owner : "Checks if the request is valid"
deactivate System

Owner -> System : "Chooses the type of the request"
activate System

System --> Owner : "Show the available types requests"
deactivate System

Owner -> System : "Chooses the type of the property"
activate System

System --> Owner : "Show the available types properties"
deactivate System

Owner -> System : "Requests the data of the property"
activate System

System --> Owner : "Requsted data type, name, address, type, description, cost"
deactivate System

alt [Apartment/House]

    System --> Owner : "Requests the data of the property"
    activate System

    Owner -> System : "Requsted data type, \n numberOfRooms, numberOfBathrooms, \n numberOfFloors, numberOfGarages, \n Equipaments, Basement, \n Inhabited, Sun exposure"
    deactivate System

    alt [House]
    System --> Owner : "Shows options for basement , inhabitable and sun exposure"
    activate System

    Owner -> System : "Choose an option"
    deactivate System

    end alt

    end alt

System --> Owner : "Shows the list of available agents"
deactivate System

Owner -> System : "Chooses an agent"
activate System

System --> Owner : "Shows the agent's data"
deactivate System

Owner -> System : "Submite the agent data"
activate System

System --> Owner : "Show the success message"
deactivate System

@enduml