@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "EmployeeProject" as User
participant ":ListAnnouncementRequestUI" as UI
participant ":CreateAnnouncementController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "AnnouncementMapper:\AnnouncementMapper" as Mapper
participant "AnnouncementDTO:\AnnouncementDTO" as DTO
participant "AnnouncementsRepository\n:AnnouncementsRepository" as REPO


activate User

User -> UI : Requests to see the list of property announcement requests
activate UI

UI -> CTRL : getPendingAnnouncementsByDate()
activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getAnnouncementsRepository()
            activate PLAT



                PLAT --> CTRL: AnnouncementsRepository
            deactivate PLAT

            CTRL -> REPO : getAnnouncementsDTO()
            loop announcementsDTO
            activate REPO
              REPO->Mapper:getAnnouncementDTO()
            activate Mapper

            Mapper->DTO:CreateAnnouncementDTO()

            activate DTO
            DTO-->Mapper:AnnouncementDTO
            deactivate DTO
            Mapper-->REPO:AnnouncementDTO
            deactivate Mapper
            end
                REPO --> CTRL : Sorted Announcements List
            deactivate REPO

CTRL --> UI : Sorted Announcements List
deactivate CTRL

UI --> User : Sorted Announcements List
deactivate UI

User -> UI : Selects a property announcement request to accept
activate UI

UI -> CTRL : changeAnnouncementState()
activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getAnnouncementsRepository()
            activate PLAT



                PLAT --> CTRL: AnnouncementsRepository
            deactivate PLAT

            CTRL -> REPO : getAnnouncementsDTO()
            loop announcementsDTO
            activate REPO
              REPO->Mapper:getAnnouncementDTO()
            activate Mapper

            Mapper->DTO:CreateAnnouncementDTO()

            activate DTO
            DTO-->Mapper:AnnouncementDTO
            deactivate DTO
            Mapper-->REPO:AnnouncementDTO
            deactivate Mapper
            end
                REPO --> CTRL : State changed successfully
            deactivate REPO

CTRL --> UI : State changed successfully
deactivate CTRL

UI -> CTRL : getPendingAnnouncementsByDate()
activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getAnnouncementsRepository()
            activate PLAT



                PLAT --> CTRL: AnnouncementsRepository
            deactivate PLAT

            CTRL -> REPO : getAnnouncementsDTO()
            loop announcementsDTO
            activate REPO
              REPO->Mapper:getAnnouncementDTO()
            activate Mapper

            Mapper->DTO:CreateAnnouncementDTO()

            activate DTO
            DTO-->Mapper:AnnouncementDTO
            deactivate DTO
            Mapper-->REPO:AnnouncementDTO
            deactivate Mapper
            end
                REPO --> CTRL : Updated Sorted Announcements List
            deactivate REPO

CTRL --> UI : Updated Sorted Announcements List
deactivate CTRL

UI --> User : Updated Sorted Announcements List
deactivate UI

@enduml
