@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction


hide circle
hide methods

class RealEstate{
   - name
   - address
   - descriptions
   - website
   - phoneNumber
   - email
   - vatNumber
   - logo

}
abstract class User{
   - name
   - descriptions
  -  tax number
  -  address
  -  email address
  -  phone number
  -  password
}

abstract class Property{
    String name;
     String type;
     String address;
     String description;
     boolean isForSale;
     boolean isForRent;
}
class StoreNetwork{
    - name
    - address
}

class Store {
    - branchNumber : int
    - designation
    - address
    - phone
    - email
    - vatNumber
    - manager
}
class Administrator{
}

class Client {
}
enum Role{
    + ROLE_STORE_MANAGER
    + ROLE_AGENT
    + ROLE_ADMIN
}

RealEstate "1"--"*" User :> has
StoreNetwork "1"--"*" Store : > has
RealEstate "1"--"1" StoreNetwork : > has

User -|>  Client : is

Client "1"--"*" Property


RealEstate "1"--"1" Administrator : > has

Administrator "1"--"*" Role

@enduml