@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "NetworkManager" as nm
participant ":ShowEmployeeUI" as UI
participant ":ShowEmployeeController" as CTRL
participant "StoreRepository:\nStoreRepository" as StoreRepository
participant "PropertyRepository:\nPropertyRepository" as PropertyRepository
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "StoreMapper:\StoreMapper" as SMapper
participant "StoreDTO:\StoreDTO" as SDTO


activate nm

        nm -> UI :  Request to list all employees
        activate UI

        UI -> CTRL** : create

        UI -> CTRL : Get Stores
        activate CTRL

CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getStoreRepository()
            activate PLAT

            PLAT --> CTRL: StoreRepository
            deactivate PLAT

CTRL -> StoreRepository : getListStoresDTO()
            loop storesDTO
            activate StoreRepository
              StoreRepository->SMapper:getListStoresDTO()
            activate SMapper

            SMapper->SDTO:CreateStoreDTO()

            activate SDTO
            SDTO-->SMapper:StoreDTO
            deactivate SDTO
            SMapper-->StoreRepository:StoreDTO
            deactivate SMapper
            end
                StoreRepository --> CTRL : StoreList
            deactivate StoreRepository

CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getPropertyRepository()
            activate PLAT

            PLAT --> CTRL: PropertyRepository
            deactivate PLAT

         CTRL->PropertyRepository: Numbers of properties of each store
         activate PropertyRepository


         PropertyRepository-->CTRL:Numbers of properties of each store
         deactivate PropertyRepository

         UI->CTRL: Get Employee

CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getStoreRepository()
            activate PLAT

            PLAT --> CTRL: StoreRepository
            deactivate PLAT

CTRL -> StoreRepository : getListEmployeeDTO()
            loop employeeDTO
            activate StoreRepository
             StoreRepository->SMapper:getListEmployeeDTO()
            activate SMapper

            SMapper->SDTO:CreateEmployeeDTO()

            activate SDTO
            SDTO-->SMapper:EmployeeDTO
            deactivate SDTO
            SMapper-->StoreRepository:EmployeeDTO
            deactivate SMapper
            end
                StoreRepository --> CTRL : EmployeeList
            deactivate StoreRepository

         CTRL->StoreRepository:getListEmployees()
         activate StoreRepository

         StoreRepository --> CTRL: List of Employee
         deactivate StoreRepository

         CTRL->CTRL:Sort employees alphabetically by store
         CTRL --> UI : Returns List of Stores and respective employees order alphabetically
         deactivate CTRL
         UI-->nm: Displays List of Stores and respective employees order alphabetically
        deactivate UI


@enduml