@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Client" as user
participant ":visitRequestUI" as visitRequestUI
participant ":visitRequestController" as visitRequestController
participant ":Repositories" as Repositories
participant ":announcementRepository" as announcementRepository
participant ":visitRequestRepository" as visitRequestRepository

activate user
user -> visitRequestUI : asks to schedule a visit

activate visitRequestUI
visitRequestUI -> visitRequestController : createVisitRequest()

activate visitRequestController

visitRequestController -> Repositories : getInstance()
activate Repositories

Repositories -> announcementRepository : getAnnouncementRepository()
activate announcementRepository

announcementRepository --> Repositories : announcementRepository()

deactivate announcementRepository

Repositories -> visitRequestRepository : getVisitRequestRepository()
activate visitRequestRepository

visitRequestRepository --> Repositories : visitRequestRepository()
deactivate visitRequestRepository

Repositories --> visitRequestController : Repositories()

deactivate Repositories
visitRequestController -> announcementRepository : getAnnouncementList()

activate announcementRepository

announcementRepository --> visitRequestController : announcementList

deactivate announcementRepository

visitRequestController --> visitRequestUI : announcementList
deactivate visitRequestController

visitRequestUI --> user : displayAnnouncementList(anncouncementList)

deactivate visitRequestUI

user -> visitRequestUI : selectAnnouncement(announcement)

activate visitRequestUI

visitRequestUI --> user : requestData(announcement)

deactivate visitRequestUI

user -> visitRequestUI : types request Data(data)

activate visitRequestUI

visitRequestUI --> user : display request Data and announcement

deactivate visitRequestUI

user -> visitRequestUI : confirmRequest()

activate visitRequestUI


'IF

alt in case of date is avaiable

    visitRequestUI -> visitRequestController : AddVisit(name, emaial, phone, date)

    activate visitRequestController
    visitRequestController -> visitRequestRepository : AddVisitData(name, emaial, phone, date)
    activate visitRequestRepository

    visitRequestRepository --> visitRequestController : VisitData
    deactivate visitRequestRepository
    visitRequestController --> visitRequestUI : VisitData
    deactivate visitRequestController
    visitRequestUI --> user : displays sucess message

    deactivate visitRequestRepository
end


'ELSE

alt else in case of date is not avaiable

visitRequestUI -> visitRequestController : AddVisitRequest(name, emaial, phone, date)

    activate visitRequestController
    visitRequestController -> visitRequestRepository : AddVisitRequestData(name, emaial, phone, date)
    activate visitRequestRepository

    visitRequestRepository --> visitRequestController : VisitRequestData
    deactivate visitRequestRepository
    visitRequestController --> visitRequestUI : VisitRequestData
    deactivate visitRequestController
    visitRequestUI --> user : displays sucess message

    deactivate visitRequestRepository
    deactivate visitRequestUI
    deactivate user
end

@enduml
