@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":visitRequestController" as visitRequestController
participant "visitRequest\n:visitRequest" as visitRequest

autonumber 2
-> visitRequestController: createVisitRequest()

autonumber 2.1
activate visitRequestController
    group Create Task

        visitRequestController -> visitRequest**: createVisitRequest()
        visitRequestController -> visitRequestController: addVisitRequest(visitRequest)

        activate visitRequestController
            visitRequestController -> visitRequestController: validateVisitRequest(visitRequest)
            activate visitRequestController
                visitRequestController --> visitRequestController
            deactivate visitRequestController

            visitRequestController --> visitRequestController
        deactivate visitRequestController
    end

    autonumber 26
    <-- visitRequestController : VisitRequestData
deactivate visitRequestController


@enduml