@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Store Manager" as st
participant ":System" as System

activate st

st -> System : Asks if the user wants to run a Simple Linear Regression or a Multiple Linear Regression
activate System

System --> st : show the values
deactivate System

deactivate st

@enduml