@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Store Manager" as st
participant ":System" as System

activate st

st -> System : asks to analyze the deals
activate System

System --> st : shows the deals
deactivate System

deactivate st

@enduml