@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Unregistered User" as ADM
participant ":CreateClientUI" as UI
participant ":CreateClientController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "ClientRepository:\nClientRepository" as ClientRepository
participant "Client\n:Client" as TAREFA


activate ADM

        ADM -> UI : Asks to register has a new User
        activate UI

            UI --> ADM : Request data (name, discription, tax number, email, password, adress, phone, roles )
        deactivate UI

        ADM -> UI : Confirms and Submits Data
        activate UI
            UI -> CTRL** : create

            UI -> CTRL : RegisterUser(name, discription, tax number, email, password, adress, phone, roles)
            activate CTRL



group Create Client
CTRL -> ClientRepository: RegisterUser(name, discription, tax number, email, password, adress, phone, roles)
                 activate ClientRepository



                             ClientRepository -> TAREFA**: RegisterUser(name, discription, tax number, email, password, adress, phone, roles)
                             ClientRepository -> ClientRepository: addClient (Client)

                             activate ClientRepository
                                 ClientRepository -> ClientRepository: validateClient(Client)
                                 activate ClientRepository
                                     ClientRepository --> ClientRepository
                                 deactivate ClientRepository

                                 ClientRepository --> ClientRepository
                             deactivate ClientRepository
end

                     ClientRepository --> CTRL : Client
                 deactivate ClientRepository
                CTRL --> UI: Client
              deactivate CTRL




            UI --> ADM : Displays Operation Sucess
        deactivate UI


@enduml