@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "System Administartor" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to legacy system data
    activate System

        System --> Employee : request File directory
    deactivate System

    Employee -> System : input file directory
    activate System


    System --> Employee : displays operation success
    deactivate System



@enduml