@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "System Administartor" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a store
    activate System

        System --> Employee : requests data
    deactivate System

    Employee -> System : types requested data (Name,Address,Description)

    activate System

    System --> Employee : displays operation success
    deactivate System

@enduml