@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Client:User" as CL
participant ":CreateOrderUI" as UI
participant ":CreateOrderController" as CTRL
participant "OrderRepository\n:OrderRepository" as ORD
participant "AnnouncementsRepository\n:AnnouncementsRepository" as ANN

activate CL

    CL -> UI :  to Buy a Property

    activate UI

        UI -> CTRL** : create
        UI -> CTRL : getAnnouncements

        ref over CTRL
            Get list of Announcements

        end ref



        activate CTRL

            CTRL -> ANN : getAnnouncements
            activate ANN

            ANN --> CTRL : AnnouncementsList

          deactivate ANN
          CTRL --> UI : AnnouncementsList
        deactivate CTRL

        UI --> CL : shows  Announcements list and asks to select one
    deactivate UI
    CL -> UI : selects an Announcements

        activate UI

            UI --> CL : requests data
        deactivate UI
        CL -> UI : types requested data (Announcements, price)
        activate UI

        UI --> CL : shows selected Announcements and requested data
        deactivate UI
        CL -> UI : submits data
     activate UI

     UI -> CTRL : createOrder(Announcements, price)
    activate CTRL
    CTRL -> CTRL : getClient from user session

      CTRL -> ORD: createOrder(Announcements, price,client)
                 activate ORD
                     ref over ORD
                         Create Order
                     end
                     ORD --> CTRL : Order
                 deactivate ORD
            CTRL --> UI: Order
              deactivate CTRL
              UI --> CL: displays operation success
      deactivate UI
deactivate CL

@enduml