@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "AnnouncementRepository\n:AnnouncementRepository" as ORG
participant "Employee\n:Employee" as TAREFA

autonumber 14
-> ORG:  createOrder(Announcement,price,Client)

autonumber 14.1
activate ORG
    group Create Employee

        ORG -> TAREFA**:  createOrder(Announcement,price,Client)
        ORG -> ORG: createOrder (Order)

        activate ORG
            ORG -> ORG: validateOrder(Order)
            activate ORG
                ORG --> ORG
            deactivate ORG

            ORG --> ORG
        deactivate ORG
    end

    autonumber 15
    <-- ORG : Order
deactivate ORG


@enduml