@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize "2"
'left to right direction
class Repositories {
  - Repositories():
  ~ propertyRepository: PropertyRepository
  ~ authenticationRepository: AuthenticationRepository
  ~ clientRepository: ClientRepository
  - instance: Repositories
  ~ announcementRepository: AnnouncementRepository
  ~ storeRepository: StoreRepository
   announcementRepository: AnnouncementRepository
   propertyRepository: PropertyRepository
   instance: Repositories
   clientRepository: ClientRepository
   authenticationRepository: AuthenticationRepository
   storeRepository: StoreRepository
}


class User {
  + User(String, String, int, String, String, String, String, Roles):
  - phone: String
  - name: String
  - email: String
  - address: String
  - taxNumber: int
  - descptions: String
  - roles: Roles
  - password: String
  + toString(): String
   name: String
   password: String
   descptions: String
   email: String
   phone: String
   address: String
   roles: Roles
   taxNumber: int
}
enum Roles << enumeration >> {
  + Roles():
  + values(): Roles[]
  + valueOf(String): Roles
}

class CreateOrderUI{
}
class CreateOrderController{
}

class Order{
    - value: int
    -Announcement: Announcement
    -Client: Client
}
class OrderDTO{
    - value: int
    -Announcement: Announcement
    -Client: Client
}

class OrderMapper{
    +OrderMapper():
    +mapToDTO(Order): OrderDTO
    +mapToEntity(OrderDTO): Order
}

User "1"--"1..*" Roles : has >
CreateOrderController .> Repositories : repositories
CreateOrderUI .> CreateOrderController
CreateOrderController ..> "1" Store : Store
Repositories "1" --> "*" StoreRepository : has >
StoreRepository "1" --> "*" Store : has >

@enduml