@startuml
title Property Registration System Use Case Diagram

actor RealEstateAgent

RealEstateAgent -> (Publish Sale Announcement): publishes
RealEstateAgent --> (View Property): views

(Publish Sale Announcement) --> System: Access system
(Publish Sale Announcement) --> System: Enter sale announcement details
(Publish Sale Announcement) --> System: Publish sale announcement

@enduml
