@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateGuestUI" as UI
participant ":CreateGuestController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "AnnouncementRepository:\AnnouncementRepository" as AnnouncementRepository


 activate UI
 UI -> CTRL : getListProperties
            activate CTRL


group Get Property List
                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getAnnouncementRepository()
                activate PLAT

                    PLAT --> CTRL: AnnouncementRepository
                deactivate PLAT

    CTRL -> AnnouncementRepository : getAnnouncementList()
             activate AnnouncementRepository

                 AnnouncementRepository --> CTRL : AnnouncementList
             deactivate AnnouncementRepository

end
                CTRL --> UI : ListProperty
            deactivate CTRL


@enduml