@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateGuestUI" as UI
participant ":CreateGuestController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "PropertyRepository:\PropertyRepository" as PropertyRepository


 activate UI
 UI -> CTRL : getListProperties
            activate CTRL


group Get Property List
                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getPropertyRepository()
                activate PLAT

                    PLAT --> CTRL: PropertyRepository
                deactivate PLAT

    CTRL -> PropertyRepository : getPropertyList()
             activate PropertyRepository

                 PropertyRepository --> CTRL : PropertyList
             deactivate PropertyRepository

end
                CTRL --> UI : ListProperty
            deactivate CTRL


@enduml