@startuml


'title Use Case Diagram Example

left to right direction
actor "Unregistered User"
actor "Agent"
actor "System Administrator"
actor "Owner"


top to bottom direction
rectangle "RealStateUSA" as usecases{
    usecase "Display listed properties"
    usecase "Publish any sale announcement"
    usecase "Register a new employee"
    usecase "Submit a request for listing a property Sale or Rent"
    usecase "Select an agent"
}
    left to right direction
    "Agent" --> "Publish any sale announcement"
    "Unregistered User" --> "Display listed properties"
    "System Administrator" --> "Register a new employee"
    "Owner" --> "Submit a request for listing a property Sale or Rent"
    "Submit a request for listing a property Sale or Rent" --> "Select an agent"
    "Agent" --> "Select an agent"
@enduml"