@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "NetworkManager" as nm
participant ":ShowEmployeeUI" as UI
participant ":ShowEmployeeController" as CTRL


activate nm

        nm -> UI :  Request to list all employees
        activate UI

        UI -> CTRL** : create

        UI -> CTRL : Get Stores
        activate CTRL

         UI->CTRL: Get Employee
       
         CTRL->CTRL:Sort employees alphabetically by store
         CTRL --> UI : Returns List of Stores and respective employees order alphabetically
         deactivate CTRL
         UI-->nm: Displays List of Stores and respective employees order alphabetically
        deactivate UI


@enduml