@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Administrator" as ADM
participant ":CreateStoreUI" as UI
participant ":CreateStoreController" as CTRL
participant ":RealEstate" as RE
participant ":StoreNetWork" as SN
participant "store\n:Store" as S

activate ADM

        ADM -> UI : asks to create a new Store

        activate UI
            UI -> CTRL** : create
            UI -> CTRL : getStoreNetWork()
            activate CTRL
            CTRL -> RE : getStoreNetWork()
                activate RE
                RE -> SN : getStoreNetWork()
                    activate SN
                    SN --> RE : StoreNetWork
                    deactivate SN
                RE--> CTRL : StoreNetWork
                deactivate RE

            CTRL --> UI : StoreNetWork
            deactivate CTRL
        UI --> ADM : requests data
        deactivate UI

        ADM ->UI : types requested data (ID, designation/name, \n location, phone number, e-mail)
        activate UI
        UI --> UI :  keepData(ID,designation/name, location,\n phone number, e-mail)
        UI--> ADM :show typed data and requests confirmation
        deactivate UI

        ADM -> UI: submit Data
        activate UI
        UI -> CTRL : createStore(ID,designation/name, location,\nphone number, e-mail)
        activate CTRL
            CTRL -> SN : createStore(ID,designation/name, location,\nphone number, e-mail)
            activate SN
            SN -> S** :createStore(ID,designation/name, location,\nphone number, e-mail)
                activate S
                    S->S : validate()
                    activate S
                    deactivate S
                deactivate S


        SN -> SN : addStore(store)
        activate SN
        SN -> SN :validateStore(store)
            activate SN
            deactivate SN
        SN --> SN
        SN --> SN
        deactivate SN

        SN --> CTRL : store
        deactivate SN
        CTRL --> UI : store
        deactivate CTRL
        UI -->ADM :Shows Operation success
        deactivate UI
        deactivate ADM
@enduml