@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0
class user{
    - name
    - descriptions
    - tax number
    - address
    - email address
    - phone number
    - password
    - roles

}

enum roles{

}

class Client extends user{
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getClientRepository()

}

@enduml