@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber
actor "Client" as cl
participant ":System" as System

activate cl

        cl -> System : to Buy a Property
    activate System

        System --> cl : shows list of Announcements and asks to select one
    deactivate System

        cl -> System : selects an Announcements
    activate System


        System --> cl : requests data
    deactivate System

        cl -> System : types requested data (Client, Property, Payment)
    activate System


        System --> cl : shows Request to confirm
    deactivate System

        cl -> System : submits Request
    activate System

        System --> cl : displays operation success
    deactivate System


@enduml