@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber
actor "Network Manager" as nm
participant ":System" as System

activate nm

    nm -> System : Ask to list all deals made
    activate System

    System --> nm : Displays list of all deals made


    System --> nm : Displays two options(ascending/descending order) to sort deals (by property area)
    deactivate System

    nm -> System : Choose sorting algorithm
    activate System


    System --> nm :Displays sorted list of deals
    deactivate System

deactivate nm
@enduml
