@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber
actor "Network Manager" as nm
participant ":System" as System

activate nm

    nm -> System : Ask to list all deals made
    activate System

    System --> nm : Displays all deals made

    System --> nm : Displays sorting algorithm

    nm -> System : Choose sorting algorithm

    System --> nm : Displays two options(ascending/descending order) to sort deals (by property area)

    nm -> System : Choose sorting option


    System --> nm :Displays sorted list of deals
    deactivate System

deactivate nm
@enduml
