@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "EmployeeProject" as User
participant ":ListAnnouncementRequestUI" as UI
participant ":CreateAnnouncementController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "AnnouncementRepository\n:AnnouncementRepository" as REPO

activate User

User -> UI : Requests to see the list of property announcement requests
activate UI

UI -> CTRL : getPendingAnnouncementsByDate()
activate CTRL

CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

CTRL -> PLAT : getAnnouncementRepository()
activate PLAT

PLAT --> CTRL: AnnouncementRepository
deactivate PLAT

CTRL -> REPO : getPendingAnnouncementsByDate()
activate REPO

REPO --> CTRL : Sorted Announcements List
deactivate REPO

CTRL --> UI : Sorted Announcements List
deactivate CTRL

UI --> User : Sorted Announcements List
deactivate UI

User -> UI : Selects a property announcement request to accept
activate UI

UI -> CTRL : changeAnnouncementState()
activate CTRL

CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

CTRL -> PLAT : getAnnouncementRepository()
activate PLAT

PLAT --> CTRL: AnnouncementRepository
deactivate PLAT

CTRL -> REPO : changeAnnouncementState()
activate REPO

REPO --> CTRL : State changed successfully
deactivate REPO

CTRL --> UI : State changed successfully
deactivate CTRL

UI -> CTRL : getPendingAnnouncementsByDate()
activate CTRL

CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

CTRL -> PLAT : getAnnouncementRepository()
activate PLAT

PLAT --> CTRL: AnnouncementRepository
deactivate PLAT

CTRL -> REPO : getPendingAnnouncementsByDate()
activate REPO

REPO --> CTRL : Updated Sorted Announcements List
deactivate REPO

CTRL --> UI : Updated Sorted Announcements List
deactivate CTRL

UI --> User : Updated Sorted Announcements List
deactivate UI

@enduml
