@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":CreateOrderController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "AnnouncementsRepository:\AnnouncementsRepository" as AnnouncementsRepository

autonumber 3

 -> CTRL : getStores()
autonumber 3.1
activate CTRL
    group Get Task Category List


            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getAnnouncementsRepository()
            activate PLAT

                PLAT --> CTRL: AnnouncementsRepository
            deactivate PLAT

            CTRL -> AnnouncementsRepository : getAnnouncementList()
            activate AnnouncementsRepository

                AnnouncementsRepository --> CTRL : AnnouncementList
            deactivate AnnouncementsRepository


    end
    autonumber 4
    <-- CTRL  : StoreList
deactivate CTRL


@enduml