@startuml

skinparam classAttributeIconSize "1"


class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getStoreRepository()
    + getEmployeeRepository()
    + getAdvertisementRepository()
    + getProprietaryRepository()
}

class AdvertisementRepository{

}

class StoreRepository{

}

class EmployeeRepository{

}

class ProprietaryRepository{

}

enum ProprietaryType{

}

class Proprietary{
    + name
    + tipo
    + address
    + descriptions
    + cost
    + vender : boolean
    + render : boolean
}

class Apartment extends Proprietary {
    + numberOfRooms
    + numberOfBathrooms
    + numberOfFloors
    + numberOfGarages
    + Equipaments
}

class House extends Proprietary {
    + numberOfRooms
    + numberOfBathrooms
    + numberOfFloors
    + numberOfGarages
    + Equipaments
}

class Land extends Proprietary{

}
'left to right direction
class CreateEmployeeUI{
}

class CreateEmployeeController{
    + CreateEmployeeController(StoreRepository)
    + createEmployee(name,descriptions,tax number,address\n,email address,phone number,password,store,roles)
}

class user{
    - name
    - descriptions
    - tax number
    - address
    - email address
    - phone number
    - password

}

enum roles{

}

class RealEstate {
    - name
    - address
    - descriptions
    - website
    - phoneNumber
    - email
    - vatNumber

}

class Employee extends user{
    -salary
}

class Administrator extends user{

}

class owner extends user{
    - Proprietary : list

    + getListOfProprietary()
}

class Store {
    - name
    - vatNumber
    - website
    - phoneNumber
    - email
    - LocalManager

}

class StoreNetWork{
    + createStore(ID, designation/name, \n location, phone number, e-mail)
    + validate(store)
    + addStore(store)
    - String name
    - String address
    - int branchNumber
}
Repositories --> "*" EmployeeRepository
Repositories --> "*" ProprietaryType
Repositories --> "*" AdvertisementRepository
Repositories --> "*" StoreRepository

Proprietary "1" -- "1" ProprietaryType : has >
Store "1" -- "0..*" Employee : has >
StoreNetWork "1" -- "0..*" Store : has >
RealEstate "1" -- "1" StoreNetWork : has >
user "1"--"1..*" roles : has >
CreateEmployeeController .> Repositories : repositories
CreateEmployeeUI .> CreateEmployeeController
Administrator --> Employee : createdBy
CreateEmployeeController ..> "1" Store : Store

@enduml