@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateAnnouncementController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "PropertyRepository:\nPropertyRepository" as PropertyRepository

autonumber 7
-> CTRL : getProperty

autonumber 7.1

activate CTRL
    group Get Property
        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getPropertyRepository()
        activate PLAT

            PLAT --> CTRL : PropertyRepository
        deactivate PLAT

        CTRL -> PropertyRepository : getPropertyList
        activate PropertyRepository

            PropertyRepository --> CTRL : PropertyList
        deactivate PropertyRepository

    end group

    autonumber 8
    <-- CTRL : PropertyList

deactivate CTRL



@enduml