@startuml
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing true
top to bottom direction

skinparam classAttributeIconSize "2"

class House{
    - numberOfRooms
    - numberOfBathrooms
    - numberOfFloors
    - numberOfGarages
    - Equipaments
    - Basement: boolean
    - inhabited  loft: boolean
    - Sun exposure: boolean
}
class Apartment{
    - numberOfRooms
    - numberOfBathrooms
    - numberOfFloors
    - numberOfGarages
    - Equipaments

}
class Land{
    - area
}
abstract class Property {
    - name
    - Tipo
    - address
    - descriptions
    - vender:boolean
    - render:boolean
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getPropertyRepository()

}
class CreateAnnouncementUI{
}

class CreateAnnouncementController{
    + createAnnouncement(Property, commission, Employee)
}
class PropertyRepository{

}

class Owner extends user{
}

class Employee extends user{
    -salary
}

class user{
    - name
    - descriptions
    - tax number
    - address
    - email address
    - phone number
    - password
    - roles

}

enum roles{

}

class Announcement{
    -Property
    -commission
    -Employee
}

class OwnerRepository{

}

CreateAnnouncementUI .> CreateAnnouncementController
CreateAnnouncementController .> Repositories : repositories
Repositories "1" --> "*" PropertyRepository : has >
PropertyRepository "1" --> "*" Property : has >
House  --|>  Property  : is
Apartment  --|>  Property : is
Land  --|>  Property : is
Owner "1"--"0.*" Property: owns
user "1"--"1..*" roles : has >
Employee "1"--"1..*" Announcement : publish >
CreateAnnouncementController ..> "1" Announcement : Announcement
OwnerRepository "1" --> "*" Owner : has >

@enduml