@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":CreateAnnouncementController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "OwnerRepository:\nOwnerRepository" as OwnerRepository

autonumber 3

 -> CTRL : getOwners()
autonumber 3.1
activate CTRL
    group Get Owners List


            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getOwnersRepository()
            activate PLAT

                PLAT --> CTRL: OwnersRepository
            deactivate PLAT

            CTRL -> OwnerRepository : getOwnersList()
            activate OwnerRepository

                OwnerRepository --> CTRL : OwnersList
            deactivate OwnerRepository


    end
    autonumber 4
    <-- CTRL  : OwnersList
deactivate CTRL


@enduml