@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class Client{
 name
 descriptions
 taxNumber
 Address
 EmailAddress
 phoneNumber
 password
}

class Agent {
}

class Store {
}

class Role {
    ROLE_REAL_ESTATE_AGENT
}

class VisitRequest {
    date
    client
    store
}

class Property {
    name
    Tipo
    address
    descriptions
    cost
}

class PropertyList {
}

Client "1" -- "1..*" VisitRequest : request >
VisitRequest "1..*" - "1" Store : register >
Store "1" - "1..*" Property : sell >
Agent "1..*" --- "1" Store : manage >
Agent "1" - "1..*" Role : has >
Property "0..*" - "1" PropertyList : contains >
Property "0..*" - "1" Agent : published >

@enduml
