@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "OrderRepository\n:OrderRepository" as ORG
participant "Order\n:Order" as TAREFA

autonumber 14
-> ORG:  createOrder(Announcement,price,Client)

autonumber 14.1
activate ORG
    group Create Employee

        ORG -> TAREFA**:  createOrder(Announcement,price,Client)

        activate ORG
            ORG -> ORG: validateOrder(Order)
            activate ORG
                ORG --> ORG
            deactivate ORG

            ORG --> ORG
        deactivate ORG
    end

    autonumber 15
    <-- ORG : Order
deactivate ORG


@enduml