@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "NetworkManager" as nm
participant ":ListDealsUI" as UI
participant ":ListDealsController" as CTRL


activate nm

    nm -> UI :  Ask List of all Deals made

    activate UI

        UI -> CTRL** : create
        UI -> CTRL : getOrdersDTO

        ref over CTRL
            Get list of Orders

        end ref

        activate CTRL

            CTRL --> UI : OrdersList
        deactivate CTRL

            UI --> nm : Displays DealsList

            UI --> nm : Displays Sort Options
       deactivate UI
       deactivate nm

    nm -> UI : User selects an Option
        activate nm
        activate UI

            UI -> CTRL : getAreaDTO
            activate CTRL

            ref over CTRL
                Get Area

            end ref
        CTRL --> CTRL: Sort by Area
        CTRL --> UI: List of Orders Sorted by Area
        deactivate CTRL
        UI-->nm: Displays DealsList Sorted by Area
        deactivate UI
        deactivate nm
@enduml