@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Organization Employee" as ADM
participant ":CreateEmployeeUI" as UI
participant ":CreateEmployeeController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "StoreRepository:\StoreRepository" as StoreRepository
participant "RealState\n:Organization" as ORG
participant "Employee\n:Employee" as TAREFA

activate ADM

    ADM -> UI : asks to create a employee

    activate UI

        UI -> CTRL** : create
        UI -> CTRL : getStores

        ref over CTRL
            Get list of stores

        end ref

        activate CTRL

            CTRL --> UI : StoresList
        deactivate CTRL

        UI --> ADM : shows  stores list and asks to select one
    deactivate UI
    ADM -> UI : selects a stores

    activate UI

    UI --> ADM : shows list of roles and asks to select one


    deactivate UI
    ADM -> UI : selects roles
        activate UI

            UI --> ADM : requests data
        deactivate UI
        ADM -> UI : types requested data (name,descriptions,tax number,address,email address\n,phone number,password)
        activate UI

        UI --> ADM : shows selected store, roles and requested data
        deactivate UI
        ADM -> UI : submits data
     activate UI

     UI -> CTRL : createEMPLOYEE(name,descriptions,tax number,address,email address\n,phone number,password,store,roles)
    activate CTRL

      CTRL -> ORG: createEMPLOYEE(name,descriptions,tax number,address,email address\n,phone number,password,store,roles)
                 activate ORG

                       group Create Employee

                             ORG -> TAREFA**: createEMPLOYEE(name,descriptions,tax number,address\n,email address,phone number,password,store,roles)
                             ORG -> ORG: addEmployee (Employee)

                             activate ORG
                                 ORG -> ORG: validateEmployee(Employee)
                                 activate ORG
                                     ORG --> ORG
                                 deactivate ORG

                                 ORG --> ORG
                             deactivate ORG
                         end

                     ORG --> CTRL : Employee
                 deactivate ORG
                CTRL --> UI: Employee
              deactivate CTRL
              UI --> ADM: displays operation success
      deactivate UI

deactivate ADM

@enduml