@startuml
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing true
top to bottom direction
left to right direction

skinparam classAttributeIconSize "2"

class VisitRequestUI {
    +chooseProperty()
    +insertData()
}

class VisitRequestController {
    + visitRequest(name: String, email: String, phone: int, date: String, property: String)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getAnnouncementsRepository()
    + getVisitRequestRepository()
    + getClientRepository()
}

class AnnouncementRepository {
  + AnnouncementRepository():
  ~ announcements: List<Announcement>
  + createAnnouncement(Property, int): Optional<Announcement>
  + addAnnouncement(Announcement): void
  + removeAnnouncement(Announcement): boolean
}

class VisitRequestRepository {
    - VisitRequestRepository()
    + getInstance() : VisitRequestRepository
    + getVisitRequestList()
    + insertVisitRequest(name: String, email: String, phone: int, date: String, property: String)
}

class ClientRepository {
  + ClientRepository():
  ~ clients: List<Client>
  - validateClient(Client): void
  + addClient(String, String, int, String, String, String, String, Roles): Optional<Client>
  + removeClient(Client): boolean
  + getClientByTaxNumber(int): Client
  + addPropertyToClient(Client, Property): void
   clients: List<Client>
}

class visitRequest {
    -String name
    -String email
    -int phone
    -String date
    -String property
    +setName
    +setEmail
    +setPhone
    +setDate
    +setProperty
}

VisitRequestUI -.> VisitRequestController
VisitRequestController -.> Repositories
Repositories -> "1" AnnouncementRepository
Repositories -> "1" VisitRequestRepository
Repositories -> "1" ClientRepository
VisitRequestRepository -.> visitRequest
ClientRepository -.> visitRequest
VisitRequestController ..> AnnouncementRepository
VisitRequestController ..> VisitRequestRepository
VisitRequestController ..> ClientRepository

@enduml