@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":CreateAnnouncementController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "ClientRepository:\nClientRepository" as ClientRepository

autonumber 3

 -> CTRL : getClients()
autonumber 3.1
activate CTRL
    group Get Client List


            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getClientRepository()
            activate PLAT

                PLAT --> CTRL: ClientRepository
            deactivate PLAT

            CTRL -> ClientRepository : getClientList()
            activate ClientRepository

                ClientRepository --> CTRL : ClientList
            deactivate ClientRepository


    end
    autonumber 4
    <-- CTRL  : ClientList
deactivate CTRL


@enduml