@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Client" as user
participant ":visitRequestUI" as visitRequestUI
participant ":visitRequestController" as visitRequestController
participant ":Repositories" as Repositories
participant ":announcementRepository" as announcementRepository
participant ":visitRequestRepository" as visitRequestRepository

activate user
user -> visitRequestUI : asks to schedule a visit

activate visitRequestUI
visitRequestUI -> visitRequestController : createVisitRequest()

activate visitRequestController

visitRequestController -> Repositories : getInstance()
activate Repositories

Repositories -> announcementRepository : getAnnouncementRepository()
activate announcementRepository

announcementRepository --> Repositories : announcementRepository()

deactivate announcementRepository

Repositories -> visitRequestRepository : getVisitRequestRepository()
activate visitRequestRepository

visitRequestRepository --> Repositories : visitRequestRepository()
deactivate visitRequestRepository

Repositories --> visitRequestController : Repositories()

deactivate Repositories
visitRequestController -> announcementRepository : getAnnouncementList()

activate announcementRepository

announcementRepository --> visitRequestController : announcementList

deactivate announcementRepository

visitRequestController --> visitRequestUI : displayAnnouncementList(announcementList)

deactivate visitRequestController

@enduml
