@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0
hide circle
hide methods
left to right direction


class Client {
    name
    descriptions
    tax number
    address
    email address
    phone number
    password
}
class Employee{
    name
    descriptions
    tax number
    address
    email address
    phone number
    password
}

enum Roles{
    ROLE_STORE_MANAGER
    ROLE_REAL_ESTATE_AGENT
}

class  RealEstateAgent{
}

class Order{
    descriptions
    client
    owner
    Property
    RealEstateAgent
}

class ApoitmentRequest{
    descriptions
    client
    owner
    Property
    RealEstateAgent
}

RealEstateAgent --|> Employee : is


@enduml