@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0
hide circle
hide methods
left to right direction


class NetWorkManager{
}

class Store{
name
vatNumber
website
phoneNumber
email
NumberOfBranches
LocalManager
}

class Employee{
    name
    descriptions
    tax number
    address
    email address
    phone number
    password
}
class StoreNetWork{
name
address
}

StoreNetWork "1"--"*" Store : has
Store "1"--"0..*" Employee : has
NetWorkManager "1"--"1" StoreNetWork: has
@enduml