@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0
hide circle
hide methods
left to right direction


class Client {
    name
    descriptions
    tax number
    address
    email address
    phone number
    password
}
class Employee{
    name
    descriptions
    tax number
    address
    email address
    phone number
    password
}

enum Roles{
    ROLE_STORE_MANAGER
    ROLE_REAL_ESTATE_AGENT
}

class  RealEstateAgent{
}

class ApoitmentRequest{
    descriptions
    client
    owner
    Property
    RealEstateAgent
}

class visit{
    Client
    date
    time
    descriptions
    RealEstateAgent
    ResultOfTheVisit : boolean
}

class Schedule{
    date
    time
    descriptions
}

RealEstateAgent --|> Employee : is
Client "1"--"1"visit : request
RealEstateAgent "1"--"1"visit : attends
RealEstateAgent "1"--"0..*"Schedule : has
Employee "1"--"1" Roles : has
ApoitmentRequest "1"--"1" Client : has
ApoitmentRequest "1"--"1" RealEstateAgent : has




@enduml