@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber
actor "Agent" as Agent
participant ":System" as System

activate Agent

    Agent -> System : Requests to see the list of property announcement requests
    activate System

    System --> Agent : Shows list of property announcement requests sorted by date (most recent first)
    deactivate System

    System --> Agent : Asks Agent to select a property announcement request to accept
    deactivate System

    Agent -> System : Selects a property announcement request to accept
    activate System

    System --> Agent : Confirms acceptance of the request and posts the announcement
    deactivate System

    System --> Agent : Refreshes the list of property announcement requests
    deactivate System

deactivate Agent

@enduml