@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateStoreController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "PropertyRepository:\nPropertyRepository" as PropertyRepository

autonumber 14
-> CTRL : getPropertyByDescription(propertyDescription)

autonumber 14.1

activate CTRL
    group Get Property
        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getPropertyRepository()
        activate PLAT

            PLAT -> CTRL : PropertyRepository
        deactivate PLAT

        CTRL -> PropertyRepository : getPropertyByDescription(propertyDescription)
        activate PropertyRepository

            PropertyRepository --> CTRL : Property
        deactivate PropertyRepository

    end group

    autonumber 15
    <-- CTRL : Property

deactivate CTRL


@enduml