@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "organization\n:Organization" as ORG
participant "property\n:property" as TAREFA

autonumber 13
-> ORG: createProperty(Owner, type, address, description, cost, vender, render, PropertyData)

autonumber 13.1
activate ORG
    group Create Task

        ORG -> TAREFA**: createProperty(Owner, type, address, description, cost, vender, render, PropertyData)
        ORG -> ORG: addProperty (Property)

        activate ORG
            ORG -> ORG: validateProperty(Property)
            activate ORG
                ORG --> ORG
            deactivate ORG

            ORG --> ORG
        deactivate ORG
    end

    autonumber 14
    <-- ORG : Property
deactivate ORG


@enduml