@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber
actor "Network Manager" as nm
participant ":System" as System

activate nm

    nm -> System : Request to list all employees
    activate System

        System -> System : Retrieve property listings for all stores
        System -> System : Retrieve employee data from all stores
        System -> System : Sort stores by number of property listings
        System -> System : Group employees by store
        System -> System : Sort employees alphabetically by store


        System --> nm : Display list of employees and property listings
    deactivate System

@enduml