@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class  RealEstateAgent{
}

class Order{
    descriptions
    client
    owner
    Property
    RealEstateAgent
}

class Client {
    name
    descriptions
    tax number
    address
    email address
    phone number
    password
}

abstract class Property {
    name
    Tipo
    address
    descriptions
    cost
    vender:boolean
    render:boolean
}


class Land{
}

class Apartment{
numberOfRooms
numberOfBathrooms
numberOfFloors
numberOfGarages
Equipaments

}
class House{
numberOfRooms
    numberOfBathrooms
    numberOfFloors
    numberOfGarages
    Equipaments
    Basement: boolean
    inhabited  loft: boolean
    Sun exposure: boolean

}


RealEstateAgent "1"--"0..*" Order : Accepts or rejects
Client "1"--"0..*" Order : Request
House  --|>  Property : is
Apartment  --|>  Property : is
RealEstate "1"--"0..*" Property : has
Land  --|>  Property : is
Order "1"--"0..*" Property : Contains



@enduml